export const AGREEMENT_NOTICE =
  'TEMPLATE FOR ATTORNEY REVIEW. This agreement is a working template generated for BBLS project coordination. It is not legal advice and must be reviewed by a licensed attorney before production use.';

export function agreementSections() {
  return [
    { id: 'parties', title: 'Parties', body: 'This Service Agreement is between BBL Boutique Brand & Launch Studio (“BBLS”), Orange County, California, and the named client identified in the proposal.' },
    { id: 'scope', title: 'Project scope', body: 'BBLS will provide the services described in the attached proposal, including the selected package, deliverables, page count, and any approved additions or custom line items.' },
    { id: 'deliverables', title: 'Deliverables', body: 'Deliverables are limited to the items listed in the proposal. Third-party accounts, licenses, stock assets, and platform subscriptions are billed separately unless expressly included.' },
    { id: 'timeline', title: 'Timeline', body: 'Streamlined launches may be completed in 14 days when scope, content, access, and approvals are ready. More customized engagements typically require 2 to 4 weeks. Timing is confirmed around readiness and is not an unconditional guarantee.' },
    { id: 'client', title: 'Client responsibilities', body: 'The client will provide timely content, access, feedback, and approvals. Delays in materials or approvals may extend the schedule.' },
    { id: 'bbls', title: 'BBLS responsibilities', body: 'BBLS will coordinate the agreed brand, website, and launch-system work with professional care and keep the client informed of project status through the private portal.' },
    { id: 'payment', title: 'Payment terms', body: 'The client will pay the project price according to the selected payment plan. Payment status is confirmed only after verified processor events. Platform subscriptions, premium assets, and approved external services are billed separately when required. Refund language, if any, must be reviewed by an attorney before production use.' },
    { id: 'revisions', title: 'Revision limits', body: 'The proposal states the number of included revision rounds. Additional revisions may require a new scope and additional fees.' },
    { id: 'changes', title: 'Change requests', body: 'Material changes to scope, pages, functionality, or creative direction after approval may be quoted as a change request before additional work begins.' },
    { id: 'delays', title: 'Project delays', body: 'If the project pauses because required content, access, or approvals are unavailable, BBLS may adjust dates after written notice in the portal.' },
    { id: 'cancel', title: 'Cancellation and termination', body: 'Either party may terminate for material breach after written notice. Compensation for work already performed is handled according to attorney-reviewed payment terms.' },
    { id: 'ip', title: 'Intellectual property', body: 'Until final approval, required payment, and formal release by BBLS, all work product remains the property of BBLS. After those conditions are met, BBLS grants the client the rights described in the attorney-reviewed final agreement.' },
    { id: 'preview', title: 'Preview and pre-approval restrictions', body: 'All concepts, drafts, previews, prototypes, designs, copy, code, images, and other work shown before final approval remain the property of BBLS. The client receives a limited right to review these materials only. The client may not publish, reproduce, distribute, copy, modify, share, transfer, use commercially, or provide the preview materials to another vendor before written final approval, completion of required payments, and formal release by BBLS. Watermarks, private preview banners, and portal authentication are deterrence and evidence measures; they do not claim to make copying technically impossible.' },
    { id: 'portfolio', title: 'Portfolio-display permission', body: 'The client may grant, refuse, or defer permission for BBLS to display the completed project after public launch. BBLS will honor the selection recorded at acceptance.' },
    { id: 'confidentiality', title: 'Confidentiality', body: 'Each party will treat non-public business information shared for the project as confidential, except for information that is public, independently developed, or required by law.' },
    { id: 'third', title: 'External services', body: 'BBLS may coordinate approved external tools, hosting platforms, payment processors, or licensed digital assets required for the website project. Those providers maintain their own terms, fees, and availability.' },
    { id: 'warranty', title: 'Warranties and limitations', body: 'PLACEHOLDER: Limitation-of-liability and warranty language must be supplied or approved by BBLS counsel before production use.' },
    { id: 'dispute', title: 'Dispute and governing-law placeholders', body: 'PLACEHOLDER: Governing law, venue, and dispute-resolution language must be supplied or approved by BBLS counsel. Do not treat this template as a complete contract.' },
    { id: 'signature', title: 'Signature and acceptance', body: 'Electronic acceptance in this portal, including typed legal name, title, company confirmation, signature, consent checkboxes, date, time, and audit metadata, is intended to evidence the client’s agreement to the then-current version of this template. Material changes create a new version and require renewed acceptance.' },
  ];
}
